#!/bin/bash

source dawn

# First convert the theme's base background values to decimal notation
col15rgbalt=$(printf "%d%d%d" 0x${col15:0:2} 0x${col15:2:2} 0x${col15:4:2})
col7rgbalt=$(printf "%d%d%d" 0x${col7:0:2} 0x${col7:2:2} 0x${col7:4:2})

# Combine the R/G/B channels of the two colours by adding each colour's
# R/G/B and dividing by 2.
col157rgb=$(printf "%d%d%d" "$(( (${col15rgbalt:0:3} + ${col7rgbalt:0:3}) / 2 ))" "$(( (${col15rgbalt:3:3} + ${col7rgbalt:3:3}) / 2 ))" "$(( (${col15rgbalt:6:3} + ${col7rgbalt:6:3}) / 2 ))")

# Then convert that into a hexadecimal value
col157=$(printf "%x%x%x" ${col157rgb:0:3} ${col157rgb:3:3} ${col157rgb:6:3})

echo $col157
